name: default
desc: This set of tasks is for default
tasks:
  - name: "EDA"
    desc: "For performing exploratory data analysis"
    guidance: |
      The current task is about exploratory data analysis, please note the following:
      - Distinguish column types with `select_dtypes` for tailored analysis and visualization, such as correlation.
      - Remember to `import numpy as np` before using Numpy functions.
  - name: "data preprocessing"
    desc: "For preprocessing dataset in a data analysis or machine learning task ONLY, general data operation doesn't fall into this type"
    guidance: |
      The current task is about data preprocessing, please note the following:
      - Monitor data types per column, applying appropriate methods.
      - Ensure operations are on existing dataset columns.
      - Avoid writing processed data to files.
      - Avoid any change to label column, such as standardization, etc.
      - Prefer alternatives to one-hot encoding for categorical data.
      - Only encode or scale necessary columns to allow for potential feature-specific engineering tasks (like time_extract, binning, extraction, etc.) later.
      - Each step do data preprocessing to train, must do same for test separately at the same time.
      - Always copy the DataFrame before processing it and use the copy to process.
  - name: "feature engineering"
    desc: "Only for creating new columns for input data."
    guidance: |
      The current task is about feature engineering. when performing it, please adhere to the following principles:
      - Generate as diverse features as possible to improve the model's performance step-by-step. 
      - Use available feature engineering tools if they are potential impactful.
      - Avoid creating redundant or excessively numerous features in one step.
      - Exclude ID columns from feature generation and remove them.
      - Each feature engineering operation performed on the train set must also applies to the test separately at the same time.
      - Avoid using the label column to create features, except for cat encoding.
      - Use the data from previous task result if exist, do not mock or reload data yourself.
      - Always copy the DataFrame before processing it and use the copy to process.
  - name: "model train"
    desc: "Only for training model."
    guidance: |
      The current task is about training a model, please ensure high performance:
      - Keep in mind that your user prioritizes results and is highly focused on model performance. So, when needed, feel free to use models of any complexity to improve effectiveness, such as XGBoost, CatBoost, etc.
      - If non-numeric columns exist, perform label encode together with all steps.
      - Use the data from previous task result directly, do not mock or reload data yourself.
      - Set suitable hyperparameters for the model, make metrics as high as possible.
  - name: "model evaluate"
    desc: "Only for evaluating model."
    guidance: |
      The current task is about evaluating a model, please note the following:
      - Ensure that the evaluated data is same processed as the training data. If not, remember use object in 'Done Tasks' to transform the data.
      - Use trained model from previous task result directly, do not mock or reload model yourself.


